#!/bin/bash
# get git data

# current location
bashdir="$(dirname -- "$0")"
cd "$bashdir"

dataRev=$(git log --oneline | wc -l | sed 's/^ *//')
dataDesc=$(git describe --tags --long)
dataV=${dataDesc%%-*}
dataHashL=$(git rev-parse HEAD)
dataHash=${dataHashL:0:8}

dateDay=$(git log -1 --date=format:'%d' --pretty=format:%cd)
dateMonth=$(git log -1 --date=format:'%m' --pretty=format:%cd)
dateYear=$(git log -1 --date=format:'%Y' --pretty=format:%cd)

# TRIM

dateDay=$(echo $dateDay | sed 's/^0*//')
dateMonth=$(echo $dateMonth | sed 's/^0*//')
dateYear=$(echo $dateYear | sed 's/^0*//')

# ECHO

echo "SpericalViewer ${dataV} - rev ${dataRev}"
echo "${dataHashL} / ${dataHash} from ${dateYear}-${dateMonth}-${dateDay}"

# JSON VERSION

genFolder="app/version"
templateFolder="templates"
versionFile="versions.json"

# make
mkdir -p "${genFolder}"

# replace
\cp -f "${templateFolder}/${versionFile}" "${genFolder}/${versionFile}"

# include data
sed -i -- 's,_$_GIT_REV_PLACEHOLDER_$_,'"${dataRev}"',g' "${genFolder}/${versionFile}"
sed -i -- 's,_$_GIT_DATE_DAY_PLACEHOLDER_$_,'"${dateDay}"',g' "${genFolder}/${versionFile}"
sed -i -- 's,_$_GIT_DATE_MONTH_PLACEHOLDER_$_,'"${dateMonth}"',g' "${genFolder}/${versionFile}"
sed -i -- 's,_$_GIT_DATE_YEAR_PLACEHOLDER_$_,'"${dateYear}"',g' "${genFolder}/${versionFile}"
sed -i -- 's,_$_GIT_HASH_PLACEHOLDER_$_,\"'"${dataHash}"'\",g' "${genFolder}/${versionFile}"
sed -i -- 's,_$_GIT_HASH_LONG_PLACEHOLDER_$_,\"'"${dataHashL}"'\",g' "${genFolder}/${versionFile}"
sed -i -- 's,_$_GIT_VER_PLACEHOLDER_$_,\"'"${dataV}"'\",g' "${genFolder}/${versionFile}"

if [ -f "${genFolder}/${versionFile}--" ]; then
	rm "${genFolder}/${versionFile}--"
fi